version: 2
jobs:
  build:
    docker:
      - image: mreichelt/android:28
    working_directory: ~/shopping-list-app
    steps:
      - checkout
      - run: mkdir artifacts
      - run:
          name: List what is currently installed
          command: sdkmanager --list
      - run:
          name: Run Android Connected Tests
          command: |
                - ./gradlew assemble
                - cp -r app/build/outputs $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: ~/home/ubuntu/shopping-list-app/app/build/outputs/apk/
          destination: env